version: '3.8'

name: jgdps

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - type: volume
        source: node_modules
        target: /workspace/node_modules
    ports:
      - 127.0.0.1:3000:3000
    command: sleep infinity

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jgdps

volumes:
  node_modules:
  db-store:
